### ISSUE TITLE
Plugin not recognized in Stream Deck App

### ISSUE THREAD

**Issue by cesteq** [hagronnestad/streamdeck-tradfri#2]
Hey hagronnestad,

just got myself a Stream Deck and wanted to give your Plugin a try, but sadly it is not recognized in Version 5.3.3.15214.

Installed it as described in the respective folder and the given name, but Stream Deck does not show any of your shortcuts. Tried rebooting the entire system, still without success.

Hope you can help me, would love to control my Tradfri lamps via the Stream Deck.

Thanks in advance, have a great day,
cesteq

**Comment by hagronnestad** [comment]
Hi @cesteq! I'm on the same version and it works for me on Windows. Are you on macOS?

**Comment by cesteq** [comment]
No I'm using Windows 10.
I've added some Plug-Ins via Stream Deck and they appear in the folder and I can use them in the Stream Deck App as they are supposed to. Even though I have added your folder, somehow Stream Deck still does not find your Tradfri Plugin :( 
Am I missing something?

**Comment by hagronnestad** [comment]
Sounds like you're doing it correctly. Are you on a 32-bit or 64-bit Windows 10 install? Maybe check for any errors in Event Viewer as well.

**Comment by cesteq** [comment]
Nothing comes up in the event monitor, but I've just found something else:

In the manifest.json file it says
`  "CodePathWin": "StreamDeckTradfri.exe",
`

even though there is no .exe file. When I change to it to .cmd the Tradfri actions are finally available in the Stream Deck App. They are not working yet, but I'll try my best to change that :D

**Comment by hagronnestad** [comment]
What? There is definitely an `.exe` file inside the ZIP-archive. If there isn't, maybe Windows or some Anti Virus incorrectly removed it.

**Comment by cesteq** [comment]
I'm very sorry, I see where I went totally wrong: I've just downloaded the code instead of the release, obviously it will not work this way.
Long story short: It works now, thank you so much! Is there any way to also set the colours in the future?

**Comment by hagronnestad** [comment]
I see 😅 Good to hear it's working now, you're welcome. I might add support for more features in the future. The best way to stay up to date is to star and watch the repository. You can set up email notifications if you so desire.

**Comment by cesteq** [comment]
I definitely will, thank you for your kindness and your time 🙌
