### ISSUE TITLE
Help for setup

### ISSUE THREAD

**Issue by BemJ77** [hagronnestad/streamdeck-tradfri#7]
Hi, 
i try to setup the plugin on my streamdeck.
The connection is ok, i've got the IP
But i don't know how to setup the light, which name i must use ?

**Comment by hagronnestad** [comment]
> Hi, i try to setup the plugin on my streamdeck. The connection is ok, i've got the IP But i don't know how to setup the light, which name i must use ?

You find the name of the devices in the IKEA Tradfri app.
